// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUieNq_wR7q4f_CGbY1yZ_WeD6Ikfn_rM',
    appId: '1:1045224735211:web:2e9adc4d1ae84f0b5119ae',
    messagingSenderId: '1045224735211',
    projectId: 'youdoyou-aeae2',
    authDomain: 'youdoyou-aeae2.firebaseapp.com',
    storageBucket: 'youdoyou-aeae2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-qelyyeku8sfN6ORkxodZC9fS7-pAkVI',
    appId: '1:1045224735211:android:3d90ecc24fdefd165119ae',
    messagingSenderId: '1045224735211',
    projectId: 'youdoyou-aeae2',
    storageBucket: 'youdoyou-aeae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARrR7g1PKhRYTHSmv9mFEUJ1QXajyaBOg',
    appId: '1:1045224735211:ios:4a9728f6d0be0f3d5119ae',
    messagingSenderId: '1045224735211',
    projectId: 'youdoyou-aeae2',
    storageBucket: 'youdoyou-aeae2.appspot.com',
    iosBundleId: 'com.example.youdoyouapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARrR7g1PKhRYTHSmv9mFEUJ1QXajyaBOg',
    appId: '1:1045224735211:ios:d5f0adfa9d1dfacb5119ae',
    messagingSenderId: '1045224735211',
    projectId: 'youdoyou-aeae2',
    storageBucket: 'youdoyou-aeae2.appspot.com',
    iosBundleId: 'com.example.youdoyou.RunnerTests',
  );
}
